# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_AlarmStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_AlarmStatus.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pb_AlarmStatus.proto\"J\n\x0epb_AlarmStatus\x12\x14\n\x0c\x61larm_active\x18\x01 \x01(\x08\x12\x10\n\x08time_utc\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61te_utc\x18\x03 \x01(\tb\x06proto3'
)




_PB_ALARMSTATUS = _descriptor.Descriptor(
  name='pb_AlarmStatus',
  full_name='pb_AlarmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarm_active', full_name='pb_AlarmStatus.alarm_active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_utc', full_name='pb_AlarmStatus.time_utc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_utc', full_name='pb_AlarmStatus.date_utc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['pb_AlarmStatus'] = _PB_ALARMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pb_AlarmStatus = _reflection.GeneratedProtocolMessageType('pb_AlarmStatus', (_message.Message,), {
  'DESCRIPTOR' : _PB_ALARMSTATUS,
  '__module__' : 'pb_AlarmStatus_pb2'
  # @@protoc_insertion_point(class_scope:pb_AlarmStatus)
  })
_sym_db.RegisterMessage(pb_AlarmStatus)


# @@protoc_insertion_point(module_scope)
