# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_Endpoint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_Endpoint.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11pb_Endpoint.proto\"S\n\x0bpb_Endpoint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08local_id\x18\x02 \x01(\t\x12\x14\n\x0c\x64omain_agent\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\tb\x06proto3'
)




_PB_ENDPOINT = _descriptor.Descriptor(
  name='pb_Endpoint',
  full_name='pb_Endpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pb_Endpoint.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_id', full_name='pb_Endpoint.local_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain_agent', full_name='pb_Endpoint.domain_agent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='pb_Endpoint.domain', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['pb_Endpoint'] = _PB_ENDPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pb_Endpoint = _reflection.GeneratedProtocolMessageType('pb_Endpoint', (_message.Message,), {
  'DESCRIPTOR' : _PB_ENDPOINT,
  '__module__' : 'pb_Endpoint_pb2'
  # @@protoc_insertion_point(class_scope:pb_Endpoint)
  })
_sym_db.RegisterMessage(pb_Endpoint)


# @@protoc_insertion_point(module_scope)
